/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorDirectory;
import model.Encounter;
import model.Patient;
import model.PatientDirectory;
import model.VitalSigns;
import model.EncounterHistory;
/**
 *
 * @author Janhvi Shah
 */
public class MainDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainDoctorJPanel
     */
    JSplitPane splitPanel;
    PatientDirectory directory;
    Doctor doctor;
    DoctorDirectory doctorDirectory;
    EncounterHistory encounterHistory;
    public MainDoctorJPanel(JSplitPane splitPanel, PatientDirectory directory, Doctor doctor, DoctorDirectory doctorDirectory, EncounterHistory encounterHistory) {
        initComponents();
        this.splitPanel = splitPanel;
        this.directory = directory;
        this.doctor = doctor;
        this.doctorDirectory = doctorDirectory;
        this.encounterHistory = encounterHistory;
        
        lblPatientID.setVisible(false);
        lblFirstName.setVisible(false);
        lblLastName.setVisible(false);
        lblAge.setVisible(false);
        lblGender.setVisible(false);
        txtPatientID.setVisible(false);
        txtFirstName.setVisible(false);
        txtLastName.setVisible(false);
        txtAge.setVisible(false);
        txtGender.setVisible(false);
        
        lblHeight.setVisible(false);
        lblWeight.setVisible(false);
        lblBP.setVisible(false);
        lblPulseRate.setVisible(false);
        lblSugarLevel.setVisible(false);
        txtHeight.setVisible(false);
        txtWeight.setVisible(false);
        txtBP.setVisible(false);
        txtPulseRate.setVisible(false);
        txtSugarLevel.setVisible(false);
        
        lblVitalSigns.setVisible(false);
        btnSaveSign.setVisible(false);
        
        txtDate.setVisible(false);
        scrollPanel.setVisible(false);
        txtDesc.setVisible(false);
        sliderSeverity.setVisible(false);
        lblDate.setVisible(false);
        lblDesc.setVisible(false);
        lblSeverity.setVisible(false);
        
        btnSaveEncounter.setVisible(false);
        lblEncounter.setVisible(false);
        
        lblPreviousEncounter.setVisible(false);
        tblEncounterHistory.setVisible(false);
//        btnViewEncounterHistory.setVisible(false);
//
//        txtEncounterHistoryDate.setVisible(false);
//        jScrollPane1.setVisible(false);
//        jScrollPane2.setVisible(false);
//        txtEncounterHistoryDescription.setVisible(false);
//        txtEncounterHistorySeverity.setVisible(false);
//        lblEncounterHistoryDate.setVisible(false);
//        lblEncounterHistoryDescription.setVisible(false);
//        lblEncounterHistorySeverity.setVisible(false);
//        txtEncounterHistoryDoctor.setVisible(false);
//        lblEncounterHistoryDoctor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearchPatient = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtPulseRate = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        lblBP = new javax.swing.JLabel();
        lblPulseRate = new javax.swing.JLabel();
        lblSugarLevel = new javax.swing.JLabel();
        txtSugarLevel = new javax.swing.JTextField();
        btnSaveSign = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        dropDownSearch = new javax.swing.JComboBox<>();
        lblEncounter = new javax.swing.JLabel();
        btnSaveEncounter = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblSeverity = new javax.swing.JLabel();
        sliderSeverity = new javax.swing.JSlider();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblVitalSigns = new javax.swing.JLabel();
        lblPreviousEncounter = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 153));

        lblTitle.setBackground(new java.awt.Color(255, 153, 153));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DOCTOR MAIN PAGE         ");

        lblSearch.setText("Search Patient:");

        txtSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPatientActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblAge.setText("Age:");

        lblGender.setText("Gender:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblPatientID.setText("Patient ID:");

        lblHeight.setText("Height:");

        lblWeight.setText("Weight:");

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });

        lblBP.setText("BP:");

        lblPulseRate.setText("Pulse Rate:");

        lblSugarLevel.setText("Sugar level:");

        txtSugarLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSugarLevelActionPerformed(evt);
            }
        });

        btnSaveSign.setText("Save Signs");
        btnSaveSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSignActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        dropDownSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient ID", "First Name" }));

        lblEncounter.setText("Add Encounter");

        btnSaveEncounter.setText("Save Encounter");
        btnSaveEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEncounterActionPerformed(evt);
            }
        });

        lblDesc.setText("Description:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        scrollPanel.setViewportView(txtDesc);

        lblSeverity.setText("Severity:");

        lblDate.setText("Date:");

        lblVitalSigns.setText("Add Vital Signs");

        lblPreviousEncounter.setText("Previous Encounters:");

        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Date", "Description", "Severity"
            }
        ));
        jScrollPane2.setViewportView(tblEncounterHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblPreviousEncounter)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(18, 18, 18)
                                .addComponent(dropDownSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFirstName)
                                            .addComponent(lblPatientID))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAge)
                                            .addComponent(lblLastName)
                                            .addComponent(lblGender))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                                .addComponent(txtAge)))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblWeight)
                                                    .addComponent(lblBP)
                                                    .addComponent(lblPulseRate))
                                                .addGap(1, 1, 1))
                                            .addComponent(lblSugarLevel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(txtWeight))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBP))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(btnSaveSign)
                                                        .addGap(0, 60, Short.MAX_VALUE))
                                                    .addComponent(txtPulseRate)
                                                    .addComponent(txtSugarLevel)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHeight)))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblVitalSigns)
                                .addGap(73, 73, 73)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDesc)
                                    .addComponent(lblSeverity)
                                    .addComponent(lblDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sliderSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPanel)
                                    .addComponent(txtDate))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEncounter)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSaveEncounter)
                                .addGap(83, 83, 83))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnLogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEncounter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPatientID)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDate)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDesc)
                                        .addGap(78, 78, 78)
                                        .addComponent(lblSeverity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sliderSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveEncounter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVitalSigns, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBP)
                            .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPulseRate))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSugarLevel)
                            .addComponent(txtSugarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveSign)))
                .addGap(8, 8, 8)
                .addComponent(lblPreviousEncounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void txtSugarLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSugarLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSugarLevelActionPerformed

    private void txtSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchPatientActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        lblPatientID.setVisible(true);
        lblFirstName.setVisible(true);
        lblLastName.setVisible(true);
        lblAge.setVisible(true);
        lblGender.setVisible(true);
        txtPatientID.setVisible(true);
        txtPatientID.setEditable(false);
        txtFirstName.setVisible(true);
        txtFirstName.setEditable(false);
        txtLastName.setVisible(true);
        txtLastName.setEditable(false);
        txtAge.setEditable(false);
        txtAge.setVisible(true);
        txtGender.setVisible(true);
        txtGender.setEditable(false);
        
        lblHeight.setVisible(true);
        lblWeight.setVisible(true);
        lblBP.setVisible(true);
        lblPulseRate.setVisible(true);
        lblSugarLevel.setVisible(true);
        txtHeight.setVisible(true);
        txtWeight.setVisible(true);
        txtBP.setVisible(true);
        txtPulseRate.setVisible(true);
        txtSugarLevel.setVisible(true);
        
        lblVitalSigns.setVisible(true);
        btnSaveSign.setVisible(true);
        
        txtDate.setVisible(true);
        Date date = new Date();
        txtDate.setText(date.toString());
        txtDate.setEditable(false);
        scrollPanel.setVisible(true);
        txtDesc.setVisible(true);
        sliderSeverity.setVisible(true);
        lblDate.setVisible(true);
        lblDesc.setVisible(true);
        lblSeverity.setVisible(true);
        
        btnSaveEncounter.setVisible(true);
        lblEncounter.setVisible(true);
        
        lblPreviousEncounter.setVisible(true);
        tblEncounterHistory.setVisible(true);
//        btnViewEncounterHistory.setVisible(true);
//
//        txtEncounterHistoryDate.setVisible(true);
//        jScrollPane1.setVisible(true);
//        jScrollPane2.setVisible(true);
//        txtEncounterHistoryDescription.setVisible(true);
//        txtEncounterHistorySeverity.setVisible(true);
//        lblEncounterHistoryDate.setVisible(true);
//        lblEncounterHistoryDescription.setVisible(true);
//        lblEncounterHistorySeverity.setVisible(true);     
//        txtEncounterHistoryDoctor.setVisible(true);
//        lblEncounterHistoryDoctor.setVisible(true);
//        
        String parameter = dropDownSearch.getSelectedItem().toString();
        String value = txtSearchPatient.getText();
        Patient  p = directory.searchPatient(parameter,value);
        txtPatientID.setText(String.valueOf(p.getPatientID()));
        txtFirstName.setText(p.getFirstName());
        txtLastName.setText(p.getLastName());
        txtAge.setText(String.valueOf(p.getAge()));
        txtGender.setText(p.getGender());
      
        if(p.getVs() != null){
            txtHeight.setText(String.valueOf(p.getVs().getHeight()));
            txtWeight.setText(String.valueOf(p.getVs().getWeight()));
            txtBP.setText(String.valueOf(p.getVs().getBp()));
            txtPulseRate.setText(String.valueOf(p.getVs().getPulseRate()));
            txtSugarLevel.setText(String.valueOf(p.getVs().getSugarLevel()));
        }
        
//        int patientID = p.getPatientID();
//        Encounter encounter = encounterHistory.searchHistory(patientID);
        populateTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private boolean isDigit(String s) {
        char[] chArr = s.toCharArray();
        for(char c: chArr) {
            if(!Character.isDigit(c))
                return false;
        }
        return true;
    }
    
    private void btnSaveSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSignActionPerformed
        // TODO add your handling code here:
        if(!isDigit(txtHeight.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter valid height!");
            return;
        }
        
        if(!isDigit(txtWeight.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter valid weight!");
            return;
        }
        if(!isDigit(txtBP.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter valid Blood Pressure!");
            return;
        }
        if(!isDigit(txtPulseRate.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter valid Pulse Rate!");
            return;
        }
        if(!isDigit(txtSugarLevel.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter valid Sugar Level!");
            return;
        }
//        int id = Integer.parseInt(txtPatientID.getText());
        Patient p = directory.searchPatient("Patient ID",txtPatientID.getText());
        float height = Float.parseFloat(txtHeight.getText());
        float weight = Float.parseFloat(txtWeight.getText());
        float bp = Float.parseFloat(txtBP.getText());
        float pulse = Float.parseFloat(txtPulseRate.getText());
        float sugar = Float.parseFloat(txtSugarLevel.getText());
        if(p.getVs() == null){
            VitalSigns vs = new VitalSigns(p.getPatientID(), height, weight, bp, pulse, sugar, doctor.getPersonID());
            p.setVs(vs);
            JOptionPane.showMessageDialog(this, "Vital Sign Record Added.");
        }
        else{
            p.getVs().setDoctorID(doctor.getPersonID());
            p.getVs().setHeight(height);
            p.getVs().setWeight(weight);
            p.getVs().setBp(bp);
            p.getVs().setPulseRate(pulse);
            p.getVs().setSugarLevel(sugar);
            JOptionPane.showMessageDialog(this, "Vital Sign Record Updated.");
        }
    }//GEN-LAST:event_btnSaveSignActionPerformed

    private void btnSaveEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEncounterActionPerformed
        // TODO add your handling code here:
        Patient  p = directory.searchPatient("Patient ID",txtPatientID.getText());
//        System.out.println(p.getPatientID());
        String date = txtDate.getText();
        String desc = txtDesc.getText();
//        System.out.println(date);
//        System.out.println(desc);
        int severity = sliderSeverity.getValue();
//        System.out.println(severity);
        
        Encounter e = new Encounter(p.getPatientID(), date, desc, severity, doctor.getPersonID());  
        encounterHistory.addEncounter(e);
        JOptionPane.showMessageDialog(this, "Encounter Record Added.");
        populateTable();
//        System.out.println("Encounter:"+p.getPatientID()+" "+date+" "+desc);
    }//GEN-LAST:event_btnSaveEncounterActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        MainJFrame topFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.loadDefaultState();
//        splitPanel.setLeftComponent(mainFrame);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSaveEncounter;
    private javax.swing.JButton btnSaveSign;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> dropDownSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblEncounter;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPreviousEncounter;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSeverity;
    private javax.swing.JLabel lblSugarLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVitalSigns;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JSlider sliderSeverity;
    private javax.swing.JTable tblEncounterHistory;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtSearchPatient;
    private javax.swing.JTextField txtSugarLevel;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        
        Patient  p = directory.searchPatient("Patient ID",txtPatientID.getText());
        int patientID = p.getPatientID();
        for(Encounter e : encounterHistory.getHistory()){
           if(e.getPatientID() == patientID){
                Object[] row = new Object[4];
                row[0] = e.getPatientID();
        //            System.out.println(".............."+row[0]);
                row[1] = e.getDate();
                row[2] = e.getDesc();
                row[3] = e.getSeverity();
//                System.out.println(".............."+row[0]+"   "+row[1]+"  "+row[2]);
                model.addRow(row);
           }
        }
    }
}
