/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import model.BookAppointmentDirectory;
import model.CityDirectory;
import model.CommunityDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author Janhvi Shah
 */
public class PatientLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientLoginJPanel
     */
    JSplitPane splitPanel;
    PatientDirectory directory;
    private int counter = 1;
    CityDirectory cityDirectory;
    CommunityDirectory communityDirectory;
    HospitalDirectory hospitalDirectory;
    EncounterHistory encounterHistory;
    BookAppointmentDirectory bookAppointmentDirectory;
    
    public PatientLoginJPanel(JSplitPane splitPanel, PatientDirectory directory, 
            CityDirectory cityDirectory, CommunityDirectory communityDirectory, HospitalDirectory hospitalDirectory, 
            EncounterHistory encounterHistory, BookAppointmentDirectory bookAppointmentDirectory) {
        initComponents();
        this.splitPanel = splitPanel;
        this.directory = directory;
        this.cityDirectory = cityDirectory;
        this.communityDirectory = communityDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.encounterHistory = encounterHistory;
        this.bookAppointmentDirectory = bookAppointmentDirectory;
//        directory = new PatientDirectory();
        
        txtLoginUsername.setVisible(false);
        txtLoginPassword.setVisible(false);
        lblLoginUsername.setVisible(false);
        lblLoginPassword.setVisible(false);
        
        btnLogin.setVisible(false);
        
        txtFirstName.setVisible(false);
        txtLastName.setVisible(false);
        txtSignUpUsername.setVisible(false);
        txtSignUpPassword.setVisible(false);
        txtAge.setVisible(false);
        txtGender.setVisible(false);
        txtMobileNo.setVisible(false);
        txtCommunity.setVisible(false);
        txtCity.setVisible(false);
        
        lblCommunity.setVisible(false);
        lblCity.setVisible(false);
        lblFirstName.setVisible(false);
        lblLastName.setVisible(false);
        lblSignUpUsername.setVisible(false);
        lblSignUpPassword.setVisible(false);
        lblAge.setVisible(false);
        lblGender.setVisible(false);
        lblMobileNo.setVisible(false);
        
        
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        btnOpenLogin = new javax.swing.JButton();
        btnOpenSignUp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtSignUpUsername = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblSignUpPassword = new javax.swing.JLabel();
        lblMobileNo = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblSignUpUsername = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtSignUpPassword = new javax.swing.JPasswordField();
        txtLoginPassword = new javax.swing.JPasswordField();
        txtGender = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));

        btnBack.setBackground(new java.awt.Color(192, 192, 192));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsernameActionPerformed(evt);
            }
        });

        lblLoginUsername.setText("Username:");

        lblLoginPassword.setText("Password:");

        btnOpenLogin.setBackground(new java.awt.Color(192, 192, 192));
        btnOpenLogin.setText("Log In");
        btnOpenLogin.setBorder(null);
        btnOpenLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLoginActionPerformed(evt);
            }
        });

        btnOpenSignUp.setBackground(new java.awt.Color(192, 192, 192));
        btnOpenSignUp.setText("Sign Up");
        btnOpenSignUp.setBorder(null);
        btnOpenSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenSignUpActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(192, 192, 192));
        btnLogin.setText("LOG IN");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtSignUpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpUsernameActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name:");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblSignUpPassword.setText("Password:");

        lblMobileNo.setText("Mobile No:");

        lblFirstName.setText("First Name:");

        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(192, 192, 192));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });

        lblSignUpUsername.setText("Username:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblAge.setText("Age:");

        lblGender.setText("Gender:");

        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " ", " " }));

        lblCommunity.setText("Community:");

        lblCity.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 715, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblSignUpUsername)
                            .addComponent(lblSignUpPassword)
                            .addComponent(lblAge)
                            .addComponent(lblGender)
                            .addComponent(lblMobileNo)
                            .addComponent(lblCommunity)
                            .addComponent(lblCity))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSignUpUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtMobileNo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtSignUpPassword)
                            .addComponent(txtGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCommunity)
                            .addComponent(txtCity)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginPassword)
                            .addComponent(lblLoginUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(txtLoginPassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpenSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLoginUsername)
                    .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginPassword)
                    .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSignUpUsername)
                    .addComponent(txtSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignUpPassword)
                    .addComponent(txtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNo)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainJFrame topFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.loadDefaultState();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void btnOpenLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLoginActionPerformed
        // TODO add your handling code here:
        txtLoginUsername.setVisible(true);
        txtLoginPassword.setVisible(true);
        lblLoginUsername.setVisible(true);
        lblLoginPassword.setVisible(true);
        
        btnLogin.setVisible(true);

    }//GEN-LAST:event_btnOpenLoginActionPerformed

    private void txtSignUpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpUsernameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private boolean isDigit(String s) {
        char[] chArr = s.toCharArray();
        for(char c: chArr) {
            if(!Character.isDigit(c))
                return false;
        }
        return true;
    }
    private boolean isLetter(String text) {
        char[] chArr = text.toCharArray();
        for(char c: chArr) {
            if(!Character.isLetter(c))
                return false;
        }
        return true;
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // Data validation
        if(String.valueOf(txtMobileNo.getText()).equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the Mobile no. field empty!");
            return;
        }
        if(!isDigit(txtMobileNo.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter mobile number!");
            return;
        }
        if(String.valueOf(txtMobileNo.getText()).length() != 10) {
            JOptionPane.showMessageDialog(this,"Please enter a valid 10 DIGIT Mobile number!");
            return;
        }
        if(txtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the First Name field empty!");
            return;
        }
        if(!isLetter(txtFirstName.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter a valid Name!");
            return;
        } 
        if(txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the Last Name field empty!");
            return;
        }
        if(!isLetter(txtFirstName.getText())) {
            JOptionPane.showMessageDialog(this,"Please enter a valid Name!");
            return;
        } 
        if(txtSignUpUsername.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the Username field empty!");
            return;
        }   
        if(txtSignUpPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the Password field empty!");
            return;
        }
        if(!isDigit(txtAge.getText())){
            JOptionPane.showMessageDialog(this,"Please enter Age number!");
            return;
        }
        if(txtCommunity.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the Community field empty!");
            return;
        } 
        if(txtCity.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please do not leave the City field empty!");
            return;
        } 
        
        // Create object of Patient
        int patientID = counter;
        counter++;
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String username = txtSignUpUsername.getText();
        String password = txtSignUpPassword.getText();
        int age = Integer.parseInt(txtAge.getText());
        String gender = txtGender.getSelectedItem().toString();
        long mobileNo = Long.parseLong(txtMobileNo.getText());
        String community = txtCommunity.getText();
        String city = txtCity.getText();
//
//                //Patient p = directory.addNewPatient();
        Patient p = new Patient();
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setUserName(username);
        p.setPassword(password);
        p.setPatientID(patientID);
        p.setAge(age);
        p.setGender(gender);
        p.setMobileNo(mobileNo);
        p.setCommunity(community);
        p.setCity(city);
        p.setRole("Patient");
        directory.addNewPatient(p);

        JOptionPane.showMessageDialog(this, "Successfull Sign Up!");

        txtFirstName.setText("");
        txtLastName.setText("");
        txtSignUpUsername.setText("");
        txtSignUpPassword.setText("");
        txtAge.setText("");
//        txtGender.setText("");
        txtMobileNo.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        
        txtFirstName.setVisible(false);
        txtLastName.setVisible(false);
        txtSignUpUsername.setVisible(false);
        txtSignUpPassword.setVisible(false);
        txtAge.setVisible(false);
        txtGender.setVisible(false);
        txtMobileNo.setVisible(false);
        txtCommunity.setVisible(false);
        txtCity.setVisible(false);
        lblCommunity.setVisible(false);
        lblCity.setVisible(false);
        lblFirstName.setVisible(false);
        lblLastName.setVisible(false);
        lblSignUpUsername.setVisible(false);
        lblSignUpPassword.setVisible(false);
        lblAge.setVisible(false);
        lblGender.setVisible(false);
        lblMobileNo.setVisible(false);
        
        btnSave.setVisible(false);
        

        System.out.println("Name:"+firstName+" "+lastName);
        System.out.println(patientID);
        System.out.println("Mobile: "+mobileNo);
        //        System.out.println("city: "+city);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnOpenSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenSignUpActionPerformed
        // TODO add your handling code here:
        txtFirstName.setVisible(true);
        txtLastName.setVisible(true);
        txtSignUpUsername.setVisible(true);
        txtSignUpPassword.setVisible(true);
        txtAge.setVisible(true);
        txtGender.setVisible(true);
        txtMobileNo.setVisible(true);
        txtCommunity.setVisible(true);
        txtCity.setVisible(true);
        lblCommunity.setVisible(true);
        lblCity.setVisible(true);
        lblFirstName.setVisible(true);
        lblLastName.setVisible(true);
        lblSignUpUsername.setVisible(true);
        lblSignUpPassword.setVisible(true);
        lblAge.setVisible(true);
        lblGender.setVisible(true);
        lblMobileNo.setVisible(true);
        
        
        btnSave.setVisible(true);
    }//GEN-LAST:event_btnOpenSignUpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtLoginUsername.getText();
        String password = txtLoginPassword.getText();
        //Boolean value = directory.authenticate(username, password);
        if(directory.authenticate(username, password)){
////    if(username.equals("drashti") && password.equals("1234")){
            JOptionPane.showMessageDialog(this, "Login Successfull!");
            txtLoginUsername.setText("");
            txtLoginPassword.setText("");
            Patient p = directory.searchPatientByUsername(username);
            MainPatientJPanel mainPatientPanel = new MainPatientJPanel(splitPanel, directory, p, cityDirectory, communityDirectory, hospitalDirectory, encounterHistory, bookAppointmentDirectory);
            splitPanel.setRightComponent(mainPatientPanel);
        } else{
            JOptionPane.showMessageDialog(this, "Login Failed!");
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        // TODO add your handling code here:
        char var = evt.getKeyChar();
        if(Character.isLetter(var)){
            txtMobileNo.setEditable(false);
            JOptionPane.showMessageDialog(null, "Character not allowed");
            txtMobileNo.requestFocus();
            txtMobileNo.setEditable(true);
        }
        String phoneNo = txtMobileNo.getText();
        int length = phoneNo.length();
        if(length>9){
            txtMobileNo.setEditable(false);
        }
        if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
            txtMobileNo.setEditable(true);
        }
    }//GEN-LAST:event_btnSaveKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOpenLogin;
    private javax.swing.JButton btnOpenSignUp;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpUsername;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JPasswordField txtSignUpPassword;
    private javax.swing.JTextField txtSignUpUsername;
    // End of variables declaration//GEN-END:variables


}
